Controllers/CodeController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
[Route("code")]
public class CodeController : Controller
{
    IFileStorage myFileStorage;
    ICompiler myCodeCompiler;
    string path;
    public CodeController(IFileStorage fileStorage, ICompiler codeCompiler)
    {
        myFileStorage = fileStorage;
        myCodeCompiler = codeCompiler;

    }
    [HttpPost("execute")]
    public JsonResult CompileAndExecute()
    {
        string IpAddress = HttpContext.Connection.RemoteIpAddress.ToString();
        path = Utilities.GetFolderName(IpAddress);

        List<string> list = new List<string>();
        foreach (var fileName in myFileStorage.GetFileNames(path))
        {
            list.Add(myFileStorage.GetFileContents(path, fileName).sourceContent);
        }
        (bool, string) res = myCodeCompiler.CompileFiles(list.ToArray(), path);
        if (res.Item1)
        {
            //make the execute request
            var executionResult = myCodeCompiler.ExecuteFiles(res.Item2, path);
            if (!executionResult.Item1)
            {
                return Json(new { code = 500, status = executionResult.Item1, message = executionResult.Item2 });
            }
            else
            {
                return Json(new { code = 200, status = executionResult.Item1, message = executionResult.Item2 });
            }
        }
        else
        {
            return Json(new { code = 500, status = res.Item1, message = res.Item2 });
        }
    }
}

Controllers/ComponentsController.cs
using System;
using Microsoft.AspNetCore.Mvc;
[Route("components")]
public class ComponentsController : Controller
{
    IFileStorage myFileStorage;
    public ComponentsController(IFileStorage fileStorage)
    {
        myFileStorage = fileStorage;
    }
    [HttpGet("sidebar")]
    public ViewComponentResult LoadSideBar()
    {
        return ViewComponent("FileList");
    }
    [HttpGet("Editor")]
    public ViewComponentResult LoadEditor(string fileName)
    {
        return ViewComponent("FileEditor",fileName);
    }
    [HttpPost("Result")]
    public ViewComponentResult ResultHandler(string result)
    {
        return ViewComponent("ResultHandler",result);
    }
}

Controllers/FileOpsHandlerController.cs
using System;
using Microsoft.AspNetCore.Mvc;
[Route("file")]
public class FileOpsHandlerController : Controller
{
    IFileStorage myFileStorage;
    string path;
    public FileOpsHandlerController(IFileStorage fileStorage)
    {
        myFileStorage = fileStorage;
      
    }

    [HttpPost("add")]
    public JsonResult AddNewFile(string name)
    {
        string IpAddress = HttpContext.Connection.RemoteIpAddress.ToString();
        path = Utilities.GetFolderName(IpAddress);
        var result = myFileStorage.AddFile(path,name);
        if (result)
        {
            return Json(new { code = 200, status = true });
        }
        else
        {
            return Json(new { code = 500, status = false, message = "Error occured while saving the file" });
        }
    }
    [HttpDelete("remove")]
    public JsonResult RemoveFile(string name)
    {
        string IpAddress = HttpContext.Connection.RemoteIpAddress.ToString();
        path = Utilities.GetFolderName(IpAddress);
        Console.WriteLine("File removed :" + name);
        var result = myFileStorage.RemoveFile(path,name);
        if (result)
        {
            return Json(new { code = 200, statusCode = true });
        }
        else
        {
            return Json(new { code = 500, statusCode = false, message = "Error occured while saving the file" });
        }
    }
    [HttpGet("listall")]
    public JsonResult GetFiles()
    {
        string IpAddress = HttpContext.Connection.RemoteIpAddress.ToString();
        path = Utilities.GetFolderName(IpAddress);
        var result = myFileStorage.GetFileNames(path);
        if (result.Length > 0)
        {
            return Json(new { code = 200, status = true });
        }
        else
        {
            return Json(new { code = 404, status = "false", message = "No File present in the location" });
        }
    }
    [HttpGet("list/{name}")]
    public JsonResult GetFileContents(string name)
    {
        string IpAddress = HttpContext.Connection.RemoteIpAddress.ToString();
        path = Utilities.GetFolderName(IpAddress);
        var result = myFileStorage.GetFileContents(path,name);
        if (result != null)
        {
            return Json(new { code = 200, status = true, result });
        }
        else
        {
            return Json(new { code = 404, status = "false", message = "No File present in the location" });
        }
    }
    [HttpPost("save")]
    public JsonResult SaveFile(string name, string sourceCode)
    {
        string IpAddress = HttpContext.Connection.RemoteIpAddress.ToString();
        path = Utilities.GetFolderName(IpAddress);
        var result = myFileStorage.SaveFile(path,name, sourceCode);
        if (result)
        {
            return Json(new { code = 200, status = true });
        }
        else
        {
            return Json(new { code = 404, status = "false", message = "No File present in the location" });
        }
    }

}

Controllers/HomeController.cs
using System;
using Microsoft.AspNetCore.Mvc;
public class HomeController : Controller
{
    [HttpGet("")]
    public ViewResult EditorPage()
    {
        return View();
    }        
}

Views/Shared/Components/FileList/FileListViewComponent.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

public class FileListViewComponent : ViewComponent
{
    IFileStorage myFileStorage;
    public FileListViewComponent(IFileStorage fileStorage)
    {
        myFileStorage = fileStorage;
    }
    public IViewComponentResult Invoke()    
    {
        string IpAddress=HttpContext.Connection.RemoteIpAddress.ToString();
        string path=Utilities.GetFolderName(IpAddress);

        var fileNames = myFileStorage.GetFileNames(path);
        return View("FilesListhandler", fileNames);
    }
}

Views/Home/EditorPage.cshtml
<div id="editorPage" class="editor" style="float: right;">
    @await Component.InvokeAsync("FileEditor", new {fileName = ""})    
</div>

<div class="sidebar">
<h4 align="center">
    <button id="newFile" style="float: right;" class="button-color"><img src="/images/file_add.png" width="16" height="20" alt="nope"></button>
    Your Files
</h4>
<div id="fileList">
    @await Component.InvokeAsync("FileList")
</div>
<br/>
<button id="Execute" onclick="compileAndExecute()" class="bar">Execute</button>    
<br/>
<label hidden id="labelWait">Please wait... while your code is executed</label>
</div>

<script src="https://code.jquery.com/jquery-1.10.2.js"></script> 
<script >
    var count=0;
    $("#newFile").click(function(){
        var url="@Url.Action("AddNewFile","FileOpsHandler")";
        count+=1;
        var name1="Hello"+count+".cs";
        $.post(url,{name:name1},function(data){
            if(data.code==200)
            {
               loadSidebar();
               loadEditorViewWithEmpty();
            }
            else{
            alert(data.message);          
            }
        });
    });
    function loadEditorViewWithEmpty()
    {
        var url="@Url.Action("LoadEditor","Components")";
                var container1=$("#editorPage");
                $.get(url,{fileName:""},function(data){
                    container1.html(data);
                });
    }
    
    function compileAndExecute()
    {
        var url="@Url.Action("CompileAndExecute","Code")";
        $("#labelWait").show();
        $.post(url,function(data){       
               $("textarea").height("45%");  
                url="@Url.Action("ResultHandler","Components")";
                var container=$("#resultHandler");
                container.show();     
                if(data.code!=200)
                {
                    $("#labelWait").hide();                    
                    alert("some error occured with message:"+data.message);
                }
                $.post(url,{result:data.message},function(data){
                    container.html(data);                    
                    $("#labelWait").hide();
                });           
        });
    }
    function loadSidebar()
    {
         url="@Url.Action("LoadSideBar","Components")";
                var container=$("#fileList");
                $.get(url,function(data){
                    container.html(data);
                });
    }
</script>